### ISSUE TITLE
Just being curious

### ISSUE THREAD

**Issue by maryamklabib** [Mithgol/efgh#1]
This is unrelated to the code but any reason why your streak on github ended? also congrats for sticking it out so long 👍

**Comment by Mithgol** [comment]
The new “Big Brother laws” in Russia are expected to put a really great burden on Internet providers and on mobile networks (basically they all are expected to store all the data they currently transmit, to store for many months, and that storage is going to be quite costly).

I've expected the prices for cable and cellular access to start raising in anticipation, at least tenfold (probably even greater), and thus I've got a feeling of an imminent end of affordable Internet access (here in Russia) as we know it. Therefore I've stopped my FLOSS experiments as meaningless (I won't need any of them in an offline country).

Five weeks later it seems that the situation was less bleak than my pessimistic view of it: the Internet is still quite affordable for the general public, the lawmakers are petitioned [by 100 098 citizens](https://www.roi.ru/28432/) to repeal those recent laws, etc. So after that time I decided that the internal cohesiveness of things might serve to hold the Internet unharmed for another couple of months or more and I've resumed my streak anew.
